name: Deploy Javascript to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Dependencies For Javascript
        run: npm install
        working-directory: javascript/angular-client

      - name: Build Javascript
        run: npm run build
        working-directory: javascript/angular-client

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: javascript/angular-client/dist/angular-client